In [ ]:
!pip install pandas==1.5.3  # Replace 1.5.3 with the appropriate version

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 88.6 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 1.5.3 which is incompatible.
mizani 0.13.1 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
xarray 2025.1.2 requires pandas>=2.1, but you have pandas 1.5.3 which is incompatible.
cudf-cu12 24.12.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.


In [ ]:
import pickle as pkl
import pandas as pd
import numpy as np
with open("CarPricesData.pkl", "rb") as f:
    object = pkl.load(f)

df = pd.DataFrame(object)
df.to_csv(r'file.csv')

In [ ]:
df

,Age,KM,Weight,HP,MetColor,CC,Doors,Price
0,23.0,46986,1165.0,90,1,2000.0,3,13500
1,23.0,72937,1165.0,90,1,2000.0,3,13750
2,24.0,41711,1165.0,90,1,2000.0,3,13950
3,26.0,48000,1165.0,90,0,2000.0,3,14950
4,30.0,38500,1170.0,90,0,2000.0,3,13750
...,...,...,...,...,...,...,...,...
1431,69.0,20544,1025.0,86,1,1300.0,3,7500
1432,72.0,19000,1015.0,86,0,1300.0,3,10845
1433,71.0,17016,1015.0,86,0,1300.0,3,8500
1434,70.0,16916,1015.0,86,1,1300.0,3,7250


from matplotlib import pyplot as plt
df['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['KM'].plot(kind='hist', bins=20, title='KM')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Weight'].plot(kind='hist', bins=20, title='Weight')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['HP'].plot(kind='hist', bins=20, title='HP')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Age', y='KM', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='KM', y='Weight', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Weight', y='HP', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='HP', y='MetColor', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['KM'].plot(kind='line', figsize=(8, 4), title='KM')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['Weight'].plot(kind='line', figsize=(8, 4), title='Weight')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['HP'].plot(kind='line', figsize=(8, 4), title='HP')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df.head(5)

,Age,KM,Weight,HP,MetColor,CC,Doors,Price
0,23.0,46986,1165.0,90,1,2000.0,3,13500
1,23.0,72937,1165.0,90,1,2000.0,3,13750
2,24.0,41711,1165.0,90,1,2000.0,3,13950
3,26.0,48000,1165.0,90,0,2000.0,3,14950
4,30.0,38500,1170.0,90,0,2000.0,3,13750


In [ ]:
df.shape

(1435, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1435 entries, 0 to 1435
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1435 non-null   float64
 1   KM        1435 non-null   int64  
 2   Weight    1435 non-null   float64
 3   HP        1435 non-null   int64  
 4   MetColor  1435 non-null   int64  
 5   CC        1435 non-null   float64
 6   Doors     1435 non-null   int64  
 7   Price     1435 non-null   int64  
dtypes: float64(3), int64(5)
memory usage: 100.9 KB


In [ ]:
target=df['Price']

In [ ]:
predictor_var=['Age','KM','Weight','HP','MetColor','CC','Doors']

In [ ]:
x=df[predictor_var].values
print(x)


[[2.3000e+01 4.6986e+04 1.1650e+03 ... 1.0000e+00 2.0000e+03 3.0000e+00]
 [2.3000e+01 7.2937e+04 1.1650e+03 ... 1.0000e+00 2.0000e+03 3.0000e+00]
 [2.4000e+01 4.1711e+04 1.1650e+03 ... 1.0000e+00 2.0000e+03 3.0000e+00]
 ...
 [7.1000e+01 1.7016e+04 1.0150e+03 ... 0.0000e+00 1.3000e+03 3.0000e+00]
 [7.0000e+01 1.6916e+04 1.0150e+03 ... 1.0000e+00 1.3000e+03 3.0000e+00]
 [7.6000e+01 1.0000e+00 1.1140e+03 ... 0.0000e+00 1.6000e+03 5.0000e+00]]


In [ ]:

y=target.values
print(y)

[13500 13750 13950 ...  8500  7250  6950]


In [ ]:
from sklearn.preprocessing import StandardScaler
predicted_scalar=StandardScaler()
target_scalar=StandardScaler()

In [ ]:
predictor_scalar_fit=predicted_scalar.fit_transform(x)
target_scalar_fit=target_scalar.fit_transform(y.reshape(-1,1))

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(predictor_scalar_fit,target_scalar_fit,test_size=0.3,random_state=42)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1004, 7)
(431, 7)
(1004, 1)
(431, 1)


In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model=Sequential()

In [ ]:
model.add(Dense(units=5,input_dim=7, kernel_initializer='normal',activation='relu'))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.add(Dense(units=5,kernel_initializer='normal',activation='tanh'))

In [ ]:
model.add(Dense(1,kernel_initializer='normal'))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 5)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 5)                   │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 78 (312.00 B)

 Trainable params: 78 (312.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='mean_squared_error',optimizer='adam')

In [ ]:
model.fit(x_train,y_train,batch_size=20,epochs=50,verbose=1)

Epoch 1/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0868
Epoch 2/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0962
Epoch 3/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0947
Epoch 4/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0949
Epoch 5/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0871
Epoch 6/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0984
Epoch 7/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0853
Epoch 8/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0878
Epoch 9/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0991
Epoch 10/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0869
Epoch 11/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0862
Epoch 12/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0894
Epoch 13/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0903
Epoch 14/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0858
Epoch 15/50
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0943
Epoch 16/50
51/51 ━

In [ ]:
model.fit(x_train,y_train,batch_size=20,epochs=32,verbose=0)

In [ ]:
prediction=model.predict(x_test)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


In [ ]:
prediction=target_scalar.inverse_transform(prediction)

In [ ]:
y_test=target_scalar.inverse_transform(y_test)

In [ ]:
test_data = predicted_scalar.inverse_transform(x_test)

In [ ]:
testing_data=pd.DataFrame(data=test_data)
testing_data.columns = predictor_var
testing_data['Price']=y_test
testing_data['Predicted Price']=prediction[:, 0]

In [ ]:
testing_data

,Age,KM,Weight,HP,MetColor,CC,Doors,Price,Predicted Price
0,59.0,80430.0,1065.0,110.0,1.0,1600.0,3.0,9950.0,9880.770508
1,62.0,64797.0,1075.0,110.0,1.0,1600.0,5.0,7995.0,10004.739258
2,59.0,130000.0,1135.0,72.0,1.0,2000.0,4.0,7500.0,8472.171875
3,69.0,42800.0,1050.0,110.0,1.0,1600.0,3.0,9950.0,9225.208984
4,65.0,47014.0,1015.0,86.0,1.0,1300.0,3.0,8950.0,8870.671875
...,...,...,...,...,...,...,...,...,...
426,73.0,176177.0,1075.0,110.0,1.0,1600.0,5.0,5950.0,7776.872559
427,11.0,12500.0,1115.0,110.0,1.0,1600.0,5.0,18900.0,20151.523438
428,56.0,35230.0,1025.0,97.0,0.0,1400.0,3.0,10950.0,10253.237305
429,56.0,19313.0,1025.0,97.0,0.0,1400.0,3.0,10500.0,10404.940430
